alias c='clear'
alias cls='clear'
alias install='sudo apt install'
alias slack='bash ~/amogus.sh; shutdown now'
alias update='sudo apt update; sudo apt upgrade; sudo apt autoremove'
alias aliases='gedit ~/.bash_aliases'
alias remove='sudo apt remove'
alias hydra='flatpak run org.gabmus.hydrapaper'
alias sus='bash ~/amogus.sh'

alias gi='git init'
alias gc='git commit'
alias gph='git push'
alias gpl='git pull'
alias gcl='git clone'
